version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=taiwanpapago
    volumes:
      - ./TAIWANpapago:/usr/src/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=taiwanpapago
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      # - ./TAIWANpapago/mysql/database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  db_data:
